spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vlbandara/config_server
          default-label: main

server:
  port: 8888